[package]
name = "ec-fan-control"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "*"
circular-queue = "*"
tokio = { version="1", features=["full"] }
async-process = "*"
ctrlc = "*"
